module FhirPackagesManager
  class Error < StandardError
  end

  class HttpError < Error
    attr_reader status: Integer?

    def initialize: (String message, Integer? status) -> void
  end

  class PackageNotFoundError < Error
  end
end
