#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
require "fhir_packages_manager"

options = { destination: "./fhir_packages", registries: [] }

parser = OptionParser.new do |opts|
  opts.banner = <<~BANNER
    Usage: fhir_packages_manager COMMAND package[@version] [package[@version] ...] [options]

    Commands:
      fetch   Download packages into the destination folder
      check   Report which registry (if any) has each package/version

  BANNER
  opts.on("-r URL", "--registry URL", "Registry base URL (repeatable, checked in order given)") do |v|
    options[:registries] << v
  end
  opts.on("-d DIR", "--destination DIR", "Destination folder for downloaded packages (default: ./fhir_packages)") do |v|
    options[:destination] = v
  end
  opts.on("-i PATH", "--ignore-file PATH", "YAML/JSON file listing packages/versions to ignore") do |v|
    options[:ignore_file] = v
  end
  opts.on("-h", "--help", "Show this help") do
    puts opts
    exit
  end
end

parser.parse!(ARGV)

command = ARGV.shift
package_specs = ARGV

if !%w[fetch check].include?(command) || package_specs.empty?
  warn parser
  exit 1
end

if options[:registries].empty?
  warn "Error: at least one --registry URL is required"
  exit 1
end

ignore_list = options[:ignore_file] ? FhirPackagesManager::IgnoreList.load(options[:ignore_file]) : nil

manager = FhirPackagesManager::Manager.new(
  registries: options[:registries],
  destination: options[:destination],
  ignore_list: ignore_list
)

case command
when "fetch"
  results = manager.fetch_all(package_specs)
  results.each do |result|
    case result.status
    when :downloaded
      puts "OK    #{result.package} -> #{result.path} (#{result.registry})"
    when :ignored
      puts "SKIP  #{result.package} (ignored)"
    when :not_found
      puts "MISS  #{result.package} (not found in any registry)"
    when :error
      puts "ERR   #{result.package}: #{result.error}"
    end
  end
  exit 1 if results.any? { |r| r.not_found? || r.error? }
when "check"
  package_specs.each do |spec|
    package = FhirPackagesManager::Package.parse(spec)
    found = manager.find_registry(package.name, package.version)
    if found
      registry, version = found
      puts "AVAILABLE   #{package.name}@#{version} (#{registry.base_url})"
    else
      puts "UNAVAILABLE #{package}"
    end
  end
end
